[2021-01-15 13:31:08,879: WARNING/ForkPoolWorker-8] Completed add_together after 10 seconds delay
[2021-01-15 13:31:18,659: WARNING/ForkPoolWorker-1] Completed add_together after 10 seconds delay

SIGHUP not supported: Restarting with SIGHUP is unstable on this platform!
[2021-01-15 13:31:22,485: ERROR/MainProcess] Process 'ForkPoolWorker-12' pid:59840 exited with 'exitcode 70'
[2021-01-15 13:31:22,498: ERROR/MainProcess] Process 'ForkPoolWorker-11' pid:59839 exited with 'exitcode 70'
[2021-01-15 13:31:22,508: ERROR/MainProcess] Process 'ForkPoolWorker-10' pid:59838 exited with 'exitcode 70'
[2021-01-15 13:31:22,519: ERROR/MainProcess] Process 'ForkPoolWorker-9' pid:59837 exited with 'exitcode 70'
[2021-01-15 13:31:22,529: ERROR/MainProcess] Process 'ForkPoolWorker-8' pid:59836 exited with 'exitcode 70'
[2021-01-15 13:31:22,542: ERROR/MainProcess] Process 'ForkPoolWorker-7' pid:59835 exited with 'exitcode 70'
[2021-01-15 13:31:22,554: ERROR/MainProcess] Process 'ForkPoolWorker-6' pid:59834 exited with 'exitcode 70'
[2021-01-15 13:31:22,567: ERROR/MainProcess] Process 'ForkPoolWorker-5' pid:59833 exited with 'exitcode 70'
[2021-01-15 13:31:22,579: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:59832 exited with 'exitcode 70'
[2021-01-15 13:31:22,589: ERROR/MainProcess] Process 'ForkPoolWorker-3' pid:59831 exited with 'exitcode 70'
[2021-01-15 13:31:22,600: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:59830 exited with 'exitcode 70'
[2021-01-15 13:31:22,612: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:59829 exited with 'exitcode 70'
[2021-01-15 13:31:38,807: WARNING/ForkPoolWorker-20] Completed add_together after 10 seconds delay
[2021-01-15 15:19:59,899: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/kombu/transport/redis.py", line 1083, in on_readable
    self.cycle.on_readable(fileno)
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/kombu/transport/redis.py", line 354, in on_readable
    chan.handlers[type]()
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/kombu/transport/redis.py", line 688, in _receive
    ret.append(self._receive_one(c))
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/kombu/transport/redis.py", line 698, in _receive_one
    response = c.parse_response()
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/Users/sergiubuhatel/development/srna-api/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2021-01-15 15:19:59,922: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2021-01-15 15:20:01,934: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2021-01-15 15:20:05,947: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2021-01-15 15:20:11,978: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2021-01-15 15:20:20,004: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2021-01-15 15:20:30,040: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2021-01-15 15:20:42,067: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[2021-01-15 15:20:56,091: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[2021-01-15 15:21:12,135: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[2021-01-15 15:21:30,183: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 20.00 seconds... (10/100)

[2021-01-15 15:21:50,234: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 22.00 seconds... (11/100)

[2021-01-15 15:22:12,297: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 24.00 seconds... (12/100)

[2021-01-15 15:22:36,365: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 26.00 seconds... (13/100)

[2021-01-15 15:23:02,459: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 28.00 seconds... (14/100)

[2021-01-15 15:23:30,532: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 30.00 seconds... (15/100)

[2021-01-15 15:24:00,600: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:24:32,701: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:25:04,826: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:25:36,879: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:26:08,956: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:26:41,037: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:27:13,117: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:27:45,198: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:28:17,308: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:28:49,359: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:29:21,443: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:29:53,501: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:30:25,570: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:30:57,640: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:31:29,750: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:32:01,823: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:32:33,894: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:33:05,959: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:33:38,046: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:34:10,119: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:34:42,204: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:35:14,281: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:35:46,355: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:36:18,433: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:36:50,503: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:37:22,572: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:37:54,655: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:38:26,704: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:38:58,806: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:39:30,879: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:40:02,951: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:40:35,008: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:41:07,080: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:41:39,198: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:42:11,286: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2021-01-15 15:45:19,491: WARNING/ForkPoolWorker-20] Completed add_together after 10 seconds delay
[2021-01-15 15:45:20,269: WARNING/ForkPoolWorker-21] Completed add_together after 10 seconds delay
[2021-01-15 16:20:28,357: WARNING/ForkPoolWorker-20] Completed add_together after 10 seconds delay
[2021-01-15 16:21:52,432: WARNING/ForkPoolWorker-20] Completed add_together after 10 seconds delay

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Sergius-MacBook-Pro-2.local v4.4.7 (cliffs)
--- ***** ----- 
-- ******* ---- macOS-10.15.7-x86_64-i386-64bit 2021-01-15 13:30:57
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         srna_api.extensions:0x7ff773a27e50
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost:6379/
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

